"""Changed Password field length again

Revision ID: 456fe9afb906
Revises: 7c27889cd9cd
Create Date: 2026-03-13 14:35:09.418449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456fe9afb906'
down_revision = '7c27889cd9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
